name: autoversion

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        name: Checkout
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Run Test
        run: yarn test

  version:
    name: Version Bump
    runs-on: self-hosted
    needs: [test]
    if: "!contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v4
        id: import_gpg
        with:
          gpg_private_key: ${{secrets.GPG_KEY}}
          passphrase: ${{secrets.GPG_PASS}}
          git_committer_name: ${{secrets.GIT_NAME}}
          git_committer_email: ${{secrets.GIT_EMAIL}}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_tag_gpgsign: true
      - name: Publish
        run: |
          git config --local gpg.program $(which gpg)
          git remote set-url origin "https://${{secrets.GIT_NAME}}:${{secrets.GIT_TOKEN}}@github.com/$GITHUB_REPOSITORY"
          yarn release
          git push --follow-tags origin main

  build:
    name: Build Image
    runs-on: self-hosted
    needs: [test]
    if: "contains(github.event.head_commit.message, 'chore(release)')"
    steps:
      - name: Get version
        id: version
        run: |
          echo "::set-output name=semver::$(git describe --tags | sed 's/v//')"
      - name: Set image tag
        id: tag
        run: |
          echo "::set-output name=bare::${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}"
          echo "::set-output name=version::${{ secrets.DOCKER_REGISTRY }}/${{ secrets.DOCKER_REPOSITORY }}:${{ steps.package_version.outputs.semver }}"
      - uses: docker/login-action@v1
        name: Login to docker registry
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build image
        run: docker build -t ${{ steps.tag.outputs.version }} .
      - name: Push image
        run: docker image push ${{ steps.tag.outputs.bare }} --all-tags
